#name of workflow
name: Hello

#triggered on
on:
  push:
      branches: [main]
      paths:
        - '**.html'
#jobs inside workflow      
jobs:
#job name
    greet:
    #github runner every job runs on runner(server)
        runs-on: ubuntu-latest
        steps:
         - name: say hello to users
           run: echo "hello user"

         - name: say hello to username
           run: echo "Hello $USER"

    details:
      runs-on: ubuntu-latest
      steps:
        - name: show version of git and docker
          run: git --version && docker --version
